const express = require('express');
const { number } = require('joi');
const stripe = require('stripe')(process.env.STRIPE_SECRET_KEY);
const createCustomer = async (req, res) => {
    try {
        const { email, name } = req.body;
        const customer = await stripe.customers.create({ email, name });
        res.status(201).json({
            message: "Customer created successfully",
            customer
        });
    }
    catch (err) {
        res.status(500).json({
            message: "Internal Server Error",
            error: err.message
        });
    }
};

//cus_TZWOVw6C00eVhG  this type of id is required here will be generated by create customer api

const addCard = async (req, res) => {
    try {
        const { customerId } = req.body;

        // 1. Create payment method using token
        const paymentMethod = await stripe.paymentMethods.create({
            type: "card",
            card: { token: "tok_visa" },
        });

        // 2. Attach the card to customer
        await stripe.paymentMethods.attach(paymentMethod.id, {
            customer: customerId,
        });

        // 3. Set as default payment method
        await stripe.customers.update(customerId, {
            invoice_settings: { default_payment_method: paymentMethod.id },
        });

        res.json({
            message: "Payment method added successfully",
            paymentMethod
        });

    } catch (err) {
        res.status(500).json({
            message: "Internal Server Error",
            error: err.message
        });
    }
};

//{
//   "customerId": "cus_TZWOVw6C00eVhG",
//   "paymentMethodId": "pm_1ScPHYQOTrRYw5eVCU6tcq6s",  //will be generated by add card api
//   "amount": 5000
// }  this is required in body

const createPaymentIntent = async (req, res) => {
    ;
    try {
        const { amount, customerId, paymentMethodId } = req.body;

        const paymentIntent = await stripe.paymentIntents.create({
            amount: 5000,
            currency: "usd",
            customer: customerId,
            payment_method: paymentMethodId,  
            confirm: true,
            off_session: true,
            automatic_payment_methods: {
                enabled: true,
                allow_redirects: "never"
            }
        });
        res.status(201).json({
            success: true,
            message: "Payment intent created successfully",
            paymentIntent
        });
    } catch (err) {
        res.status(500).json({
            success: false,
            message: "Internal Server Error",
            error: err.message
        });
    }
}

// you will get an session id from here
const createCheckoutSession = async (req, res) => {
    try {
        const session = await stripe.checkout.sessions.create({
            payment_method_types: ['card'],
            line_items: [{
                price_data: {
                    currency: 'usd',
                    product_data: {
                        name: 'T-shirt',
                    },
                    unit_amount: 2000,
                },
                quantity: 1,
            }],
            mode: 'payment',
            success_url: 'https://example.com/success',
            cancel_url: 'https://example.com/cancel',
        });

        res.status(200).json({
            success: true,
            message: "Checkout session created successfully",
            sessionId: session.id
        });
    } catch (err) {
        res.status(500).json({
            success: false,
            message: "Internal Server Error",
            error: err.message
        });
    }
}
module.exports = {
    createCustomer,
    addCard,
    createPaymentIntent,
    createCheckoutSession
};